### PR TITLE
Update 1.5

### PR DESCRIPTION
**Pull request by webketje**
* Upgrades jQuery dataTables from 1.10.7 => 1.10.19, and showdown.js from 1.8 => 1.9
* Adds Last updated date to DataTables
* Fixes some markdown parsing issues, adds display of DataTables sort icons, and some styling enhancements 
* Makes DataTables orderable by Installed/ Not installed plugins & searchable by author + plugin name

### CODE REVIEW

**Comment by HelgeSverre** [comment]
Thanks!

I'll merge this in and push out a new version to the extend repo tomorrow

**Comment by webketje** [comment]
@HelgeSverre No thanks to you! I was looking at the "Most downloaded plugins" for recent months and realize this is an important one for the small GS community, so it is worth improving :)

**Comment by HelgeSverre** [comment]
Extend seems to be broken temporarily, I get an "internal server error" when trying to update/upload the new version.

**Comment by webketje** [comment]
@HelgeSverre Might be worth giving it another try if you have some time, I saw some new plugins have been uploaded.

**Comment by HelgeSverre** [comment]
@webketje will resubmit now

**Comment by HelgeSverre** [comment]
image
 :(

**Comment by webketje** [comment]
@HelgeSverre I don't want to push here, but I uploaded a new version of Components Extended yesterday and it worked like this: first try - fail, click browser back button, re-attach the ZIP, re-submit => success. There's [a thread about this issue](http://get-simple.info/forums/showthread.php?tid=10666&pid=63760) on the forums should you be interested.

**Comment by HelgeSverre** [comment]
Hmm I will try again

**Comment by HelgeSverre** [comment]
Hmm did not work, tried multiple times.

**Pull request merged**
